// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOPCIaHG0Ys0O02wKOAVkgxhcoC6WXdN4',
    appId: '1:330231237206:web:0b3c8fabe720904c0ec9f7',
    messagingSenderId: '330231237206',
    projectId: 'expencetracker-1f4b3',
    authDomain: 'expencetracker-1f4b3.firebaseapp.com',
    storageBucket: 'expencetracker-1f4b3.appspot.com',
    measurementId: 'G-LQX0GG2W5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WJUGvx5eOtU4G6V5dJRKB17htVanbbY',
    appId: '1:330231237206:android:5c7f38176e85aac00ec9f7',
    messagingSenderId: '330231237206',
    projectId: 'expencetracker-1f4b3',
    storageBucket: 'expencetracker-1f4b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMJLhd0OmjeuO-aXeGA98d8gSvb9Acb6k',
    appId: '1:330231237206:ios:784778a555732b0c0ec9f7',
    messagingSenderId: '330231237206',
    projectId: 'expencetracker-1f4b3',
    storageBucket: 'expencetracker-1f4b3.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMJLhd0OmjeuO-aXeGA98d8gSvb9Acb6k',
    appId: '1:330231237206:ios:784778a555732b0c0ec9f7',
    messagingSenderId: '330231237206',
    projectId: 'expencetracker-1f4b3',
    storageBucket: 'expencetracker-1f4b3.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOPCIaHG0Ys0O02wKOAVkgxhcoC6WXdN4',
    appId: '1:330231237206:web:3c87acf7c03a91770ec9f7',
    messagingSenderId: '330231237206',
    projectId: 'expencetracker-1f4b3',
    authDomain: 'expencetracker-1f4b3.firebaseapp.com',
    storageBucket: 'expencetracker-1f4b3.appspot.com',
    measurementId: 'G-QJDGDHM817',
  );
}
